### ISSUE TITLE
Status of tabulator-qt

### ISSUE THREAD

**Issue by robochat** [notnypical/tabulator-qt#1]
Hi, I managed to compile the application and run it but nothing happens when I load a csv file. What's the current status of the program? I'm looking for a super light-weight csv viewer for linux so tabulator-qt is really interesting for me.

**Comment by notnypical** [comment]
Tabulator-Qt will be a lightweight viewer and editor for CSV files for Linux. But the development is still in the early stages. The viewer will be ready in about 2-3 weeks and the editor in 5-6 weeks.
